Change the logo to link to the LMS
openedx/frontend-component-footer pull request #178
Opened 2022-02-09 01:54 UTC by ayrtonlr

# Description

Changed the hard-coded link of the Logo to the LMS_BASE_URL config variable, since it is required for Open edX micro-frontends and it points to the fully-qualified URL to the LMS.

# Useful information to include:

Related issue: https://github.com/openedx/build-test-release-wg/issues/128

# Testing instructions

Click on the logo that is located in the bottom left corner and check that you are not redirected to: https://open.edx.org/
Now, the link is to the LMS.

2022-02-09 01:54 UTC, edx-webhook commented
Thanks for the pull request, @ayrtonlr! I've created [OSPR-6444](https://openedx.atlassian.net/browse/OSPR-6444) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-02-09 19:38 UTC, sarina commented
hello & welcome @ayrtonlr ! I ran the tests on your fix and it looks like one failed (I'm unfortunately not a good person to ask about MFEs and the way they're tested). Could you look into it?

2022-02-09 20:08 UTC, ayrtonlr commented
Hello @sarina , thank you.

I think I fixed the tests. Could you run them again?
Thanks.

2022-02-09 20:54 UTC, sarina commented
yay, they passed! I know someone from BTR is working on finding a good reviewer for your changes. Thanks again for your contribution 😁

2022-02-11 15:39 UTC, natabene commented
@ayrtonlr Thank you for your contribution! @arbrandes Thanks for looking into this.

2022-02-11 16:10 UTC, ayrtonlr commented
@sarina @arbrandes @natabene Thank you guys. Please let me know if you need any changes.

2022-02-11 18:06 UTC, natabene commented
@arbrandes Will you merge as well when time comes?

2022-02-11 18:09 UTC, arbrandes commented
@arbrandes, that's the idea, yes.

Though first I'll have to petition expanding my commit access to this particular repo.  Even though I'm at tCRIL now, we want our developers to have to go through the same process as anybody in the community.

Which is to say, @ayrtonlr, this might take a week or two, if you don't mind.

2022-03-02 06:59 UTC, BbrSofiane commented
Bringing this back to your attention @arbrandes

2022-03-21 13:39 UTC, arbrandes commented
@BbrSofiane, @giovannicimolin, apologies for the delay.  I'll do a proper review this week.

2022-03-23 17:36 UTC, arbrandes requested changes
@ayrtonlr, this looks great, thanks!  I tested it locally, and the change works as intended.

Do you mind rebasing on master and squashing all commits into one, please?  It's fine to leave it as a "fix:".

2022-03-23 23:24 UTC, ayrtonlr commented
@arbrandes Done, I squashed all commits into just one.

2022-03-24 09:44 UTC, arbrandes approved these changes

2022-03-24 09:46 UTC, merged

2022-03-24 09:46 UTC, edx-webhook commented
@ayrtonlr 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-component-footer&entry.867055334=https://github.com/openedx/frontend-component-footer/pull/178&entry.1484655318=https://github.com/ayrtonlr&entry.752974735=2022-02-09+01:54&entry.1917517419=2022-03-24+09:46&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->