feat!: remove Transifex calls for OEP-58 | FC-0012
openedx/frontend-component-footer pull request #355
Opened 2023-10-21 09:02 UTC by hopewise

## Breaking change!

This change breaks the Jenkins transifex integration which has been deprecated in favor of the new GitHub Transifex App integration as part of [OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

## Changes

 - Removes all direct use of `tx pull` and `tx push` commands from the micro-frontend in favor
of the [`atlas pull`](https://github.com/openedx/openedx-atlas/) command.
 - Remove source and language translations from the repositories, hence no `.json` files will be committed into the repos. 
 - `src/i18n/index.js` should export and empty array so the `make pull_translations` override it with the dynamic list of languages.
 - Remove the experimental `OPENEDX_ATLAS_PULL` flag to make `atlas pull` the default. 
 - Remove all Transifex related `Makefile` targets and other files.

Test results
------------

 - [ ] Verify that `make pull_translations` works as expected.

<details><summary>make pull_translations test results</summary>

```
# I've run the following commands:
$ make requirements
$ make pull_translations
$ git diff

# Output of the commmands:

make pull_translations
rm -rf src/i18n/messages
mkdir src/i18n/messages
cd src/i18n/messages \
      && atlas pull \
               translations/paragon/src/i18n/messages:paragon \
               translations/frontend-component-header/src/i18n/messages:frontend-component-header \
               translations/frontend-component-footer/src/i18n/messages:frontend-component-footer \
               translations/frontend-app-profile/src/i18n/messages:frontend-app-profile
Pulling translation files
 - directory: translations/paragon/src/i18n/messages:paragon translations/frontend-component-header/src/i18n/messages:frontend-component-header translations/frontend-component-footer/src/i18n/messages:frontend-component-footer translations/frontend-app-profile/src/i18n/messages:frontend-app-profile
 - repository: openedx/openedx-translations
 - branch: main
 - filter: Not Specified
 - expand-glob: Not Specified
Creating a temporary Git repository to pull translations into "./translations_TEMP"...
Done.
Setting git sparse-checkout rules...
Done.
Pulling translation files from the repository...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 58 (delta 38), reused 39 (delta 26), pack-reused 0
Receiving objects: 100% (58/58), 49.75 KiB | 727.00 KiB/s, done.
Resolving deltas: 100% (38/38), done.
Your branch is up to date with 'origin/main'.
Done.
Copying translations from "./translations_TEMP/translations/paragon/src/i18n/messages" to "./paragon"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-component-header/src/i18n/messages" to "./frontend-component-header"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-component-footer/src/i18n/messages" to "./frontend-component-footer"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-app-profile/src/i18n/messages" to "./frontend-app-profile"...
Done.
Removing temporary directory...
Done.

Translations pulled successfully!
paragon frontend-component-header frontend-component-footer frontend-app-profile
make: paragon: No such file or directory
make: *** [pull_translations] Error 1

```

</details> 

Merge timeline
-----------------------

This should only be merged after [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification) is fully implemented.

The timing announcement will be shared by @brian-smith-tcril on [#translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T) Open edX Slack channel.

Keep this pull request as a draft to prevent accidental merge.

### Pre-merge checklist

 - [ ] Wait for approval on https://github.com/openedx/wg-translations/issues/20

References
----------

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

2023-10-21 09:02 UTC, openedx-webhooks commented
Thanks for the pull request, @hopewise!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2023-10-24 14:30 UTC, e0d commented
@hopewise looks like there are some test failures.

2023-10-28 14:07 UTC, hopewise commented
a new line added to the `src/i18n/index.js`, to allow test to pass.

2023-10-28 20:41 UTC, OmarIthawi requested changes
Please remove the `pull_translations` step altogether. Other MFEs will pull translations for the footer.

2023-11-10 10:35 UTC, hopewise commented on Makefile
>  pull_translations:
@OmarIthawi ok, I removed the `pull_translations `

2024-02-15 09:33 UTC, OmarIthawi approved these changes
Looks good. I've merged one fix.

2024-02-15 09:33 UTC, OmarIthawi commented on src/i18n/index.js
> +export default [];
One more fix.

```suggestion
export default {};
```

2024-03-17 13:11 UTC, OmarIthawi commented
@timmc-edx this one is ready but pending 2U approval.

cc: @brian-smith-tcril

2024-03-18 13:44 UTC, brian-smith-tcril approved these changes

2024-03-23 04:06 UTC, OmarIthawi commented
@brian-smith-tcril rebased.

2024-03-25 15:15 UTC, OmarIthawi commented
@brian-smith-tcril rebased :)

2024-03-25 15:23 UTC, merged

2024-03-25 15:23 UTC, openedx-webhooks commented
@hopewise 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-component-footer&entry.867055334=https://github.com/openedx/frontend-component-footer/pull/355&entry.1484655318=https://github.com/hopewise&entry.752974735=2023-10-21+09:02&entry.1917517419=2024-03-25+15:23&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->